codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 100%
        threshold: 0%

ignore:
  - SDKAndroid/src/main/kotlin/app/cybrid/sdkandroid/components
  - SDKAndroid/src/main/kotlin/app/cybrid/sdkandroid/flow
  - SDKAndroid/src/main/kotlin/app/cybrid/sdkandroid/util/UtilsComposable.kt
  - SDKAndroid/src/main/kotlin/app/cybrid/sdkandroid/core/Constants.kt
  - SDKAndroid/src/main/kotlin/app/cybrid/sdkandroid/ui

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true