version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  android: circleci/android@2.1.2

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  android-test:
    docker:
      - image: cimg/android:2022.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: |
            ./gradlew SDKAndroid:androidDependencies
      - run:
          name: Run Tests
          command: |
            ./gradlew koverXmlReport
      - store_artifacts:
          path: SDKAndroid/build/reports/kover/project-xml/report.xml
          destination: reports
      - codecov/upload:
          file: 'SDKAndroid/build/reports/kover/project-xml/report.xml'
      - when:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Update version tag
                command: |
                  export TAG=$(git describe --tags --abbrev=0)
                  sed -i "s/0.0.0/$TAG/" version.gradle
            - run:
                name: Publish Library
                command: |
                  ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

workflows:
  android-test:
    jobs:
      - android-test