version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  android: circleci/android@2.3.0

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:

  android-sdk-test:
    docker:
      - image: cimg/android:2023.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "SDKAndroid/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            ./gradlew SDKAndroid:androidDependencies
      - run:
          name: Run SDK Unit Test
          command: |
            ./gradlew koverXmlReport
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "SDKAndroid/build.gradle" }}
      - codecov/upload:
          file: 'SDKAndroid/build/reports/kover/xml/report.xml'

  android-e2e:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.06.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - run:
          name: Run UI Test
          command: |
            ./gradlew app:connectedDebugAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1a

  android-sdk-publish:
    docker:
      - image: cimg/android:2023.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - when:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Download Dependencies
                command: |
                  ./gradlew SDKAndroid:androidDependencies
            - save_cache:
                paths:
                  - ~/.gradle
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Update version tag
                command: |
                  export TAG=$(git describe --tags --abbrev=0)
                  sed -i "s/0.0.0/$TAG/" version.gradle
            - run:
                name: Publish Library
                command: |
                  ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

  firebase-robo:
    docker:
      - image: cimg/android:2023.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
              ./gradlew SDKAndroid:androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Compile Debug App
          command: |
              ./gradlew app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debugAPK
      - run:
          name: Set Firabse FIREBASE_SERVICE_ACCOUNT_KEY
          command: echo ${FIREBASE_SERVICE_ACCOUNT_KEY} | base64 -di > ${HOME}/client-secret.json
      - run:
          name: Authenticate with Google Cloud
          command: |
              sudo gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
              sudo gcloud --quiet config set project ${FIREBASE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: |
              sudo gcloud firebase test android run \
               --type robo \
               --app app/build/outputs/apk/debug/app-debug.apk \
               --device model=oriole,version=31,locale=en,orientation=portrait \
               --timeout 15m

  demo-app-publish:
    docker:
      - image: cimg/android:2023.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
              ./gradlew SDKAndroid:androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Compile Debug App
          command: |
              ./gradlew app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debugAPK
      - run:
          name: Upload app to Appetize
          command: |
              curl --http1.1 https://${APPETIZE_API_TOKEN}@api.appetize.io/v1/apps/${APPETIZE_PUBLIC_API_TOKEN} -F "file=@app/build/outputs/apk/debug/app-debug.apk" -F "platform=android"

workflows:
  android-test:
    jobs:
      - android-sdk-test
      - android-e2e
      - android-sdk-publish:
          requires:
            - android-sdk-test
            - android-e2e
          filters:
            branches:
              only:
                - main
      - firebase-robo:
          requires:
            - android-e2e
          filters:
            branches:
              only:
                - main
      - demo-app-publish:
          requires:
            - android-e2e
            - firebase-robo
          filters:
            branches:
              only:
                - main