version: 2.1

setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.3.0

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: file-changes/filter
          mapping: |
            sdk-android/.* android-test true