version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  android: circleci/android@2.1.2

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:

  android-sdk-publish:
    docker:
      - image: cimg/android:2022.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - when:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Download Dependencies
                command: |
                  ./gradlew SDKAndroid:androidDependencies
            - save_cache:
                paths:
                  - ~/.gradle
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Update version tag
                command: |
                  export TAG=$(git describe --tags --abbrev=0)
                  sed -i "s/0.0.0/$TAG/" version.gradle
            - run:
                name: Publish Library
                command: |
                  ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

  android-e2e:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - run:
          name: Run UI Test
          command: |
            ./gradlew app:connectedDebugAndroidTest
      - run:
          name: Run Unit Test
          command: |
            ./gradlew app:testDebugUnitTest
      - android/save-gradle-cache:
          cache-prefix: v1a

  android-sdk-test:
    docker:
      - image: cimg/android:2022.06.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            ./gradlew SDKAndroid:androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run SDK Unit Test
          command: |
            ./gradlew koverXmlReport
      - store_artifacts:
          path: SDKAndroid/build/reports/kover/project-xml/report.xml
          destination: reports
      - codecov/upload:
          file: 'SDKAndroid/build/reports/kover/project-xml/report.xml'
      - when:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Update version tag
                command: |
                  export TAG=$(git describe --tags --abbrev=0)
                  sed -i "s/0.0.0/$TAG/" version.gradle
            - run:
                name: Publish Library
                command: |
                  ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

workflows:
  android-test-publish:
    jobs:
      - android-sdk-test
      - android-e2e
      - android-sdk-publish:
          requires:
            - android-sdk-test
            - android-e2e